spring:
  application:
    # Never use '_' in application name
    # Use '-' instead
    # Otherwise gateway may not work correctly
    name: payment-microservice
  config:
    import: configserver:http://localhost:8888
    # Message queue
  cloud:
    stream:
      kafka:
        binder:
        # Kafka server URL
        # 9092 is the default port of Kafka
          brokers: localhost:9092
      bindings:
        # https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/functional-binding-names.html
        # Format: <method name>-<in or out>-<index>
        # sendMessage: name of the method that sends the message
        # out: because is a consumer
        # 0: Index of the binding. This makes sense when the same method sends to multiple queues
        receiveOrder-in-0:
        # Name of the queue that will manage the messages
          destination: order-payment-queue
          group: my-consumer-group
        sendStatus-out-0:
          destination: payment-order-queue